version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: todolist-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todolist_db
    ports:
      - "5432:5432"
    networks:
      - to_do_network
  backend:
    build: /Backend
    container_name: backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://todolist-db:5432/todolist_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8081:8081"
    networks:
      - to_do_network
  frontend:
    build: /frontend
    container_name: frontend_container
    ports:
      - "8082:80"
    networks:
      - to_do_network
networks:
  to_do_network:
volumes:
  pgdata:
